# -*- coding: utf-8 -*-
"""Linear_Regression_Tensorflow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BkwEEC7wd-Jj8Prxx2YHr3Nl0x3KXuRt
"""

import sys
import time
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.examples.tutorials.mnist import input_data
# %matplotlib inline

# %load_ext autoreload
# %autoreload 2

MNIST = input_data.read_data_sets("MNIST_data", one_hot=True)

#Define parameter for Linear model
learning_rate = 0.01
batch_size= 128 
number_epochs=25

#Create placeholders
X = tf.placeholder(tf.float32, [batch_size, 784], name="image")
Y = tf.placeholder(tf.float32, [batch_size, 10], name="label")

#Create weights and bias
w = tf.Variable(tf.random_normal(shape=[784, 10], stddev=0.1), name="weights")
b = tf.Variable(tf.zeros([1,10]), name= 'bias')